# Generated by Django 4.2.5 on 2023-10-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
