# Generated by Django 4.2.5 on 2023-10-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0005_reg_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
