# Generated by Django 4.2.5 on 2023-10-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0006_delete_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsystem',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
